"""Add agent_mastery_stats table

Revision ID: 05668d85b9e1
Revises: 45936138fcee
Create Date: 2026-05-03 22:06:11.514061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05668d85b9e1'
down_revision: Union[str, Sequence[str], None] = '45936138fcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_mastery_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('rapport_building', sa.Float(), nullable=True),
    sa.Column('emotional_sync', sa.Float(), nullable=True),
    sa.Column('ownership_trust', sa.Float(), nullable=True),
    sa.Column('process_clarity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_mastery_stats_employee_id'), 'agent_mastery_stats', ['employee_id'], unique=True)
    op.create_index(op.f('ix_agent_mastery_stats_id'), 'agent_mastery_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'transcript',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_mastery_stats_id'), table_name='agent_mastery_stats')
    op.drop_index(op.f('ix_agent_mastery_stats_employee_id'), table_name='agent_mastery_stats')
    op.drop_table('agent_mastery_stats')
    # ### end Alembic commands ###
