"""add_auth_and_roles

Revision ID: 26484e912d16
Revises: 50f4eedcc998
Create Date: 2026-05-03 03:00:10.010630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26484e912d16'
down_revision: Union[str, Sequence[str], None] = '50f4eedcc998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default='change_me_later'))
        batch_op.add_column(sa.Column('role', sa.Enum('AGENT', 'QA', 'ADMIN', name='userrole'), nullable=False, server_default='agent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('hashed_password')
    # ### end Alembic commands ###
