"""add_system_log_fields

Revision ID: 33ab3b62a1ac
Revises: 26484e912d16
Create Date: 2026-05-03 03:12:50.824236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ab3b62a1ac'
down_revision: Union[str, Sequence[str], None] = '26484e912d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('system_logs', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_logs', 'resolved')
    op.drop_column('system_logs', 'severity')
    # ### end Alembic commands ###
