"""Add HR_MANAGER role and phone_number to Employee

Revision ID: 4765f94e7c15
Revises: 05668d85b9e1
Create Date: 2026-05-03 23:40:29.437593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4765f94e7c15'
down_revision: Union[str, Sequence[str], None] = '05668d85b9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('AGENT', 'QA', 'ADMIN', 'HR_MANAGER', name='userrole'),
               existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'role',
               existing_type=sa.Enum('AGENT', 'QA', 'ADMIN', 'HR_MANAGER', name='userrole'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'agent'"))
    op.drop_column('employees', 'phone_number')
    op.alter_column('calls', 'transcript',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
