"""add_agent_email

Revision ID: 50f4eedcc998
Revises: b374524c5bba
Create Date: 2026-05-03 02:56:41.848006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f4eedcc998'
down_revision: Union[str, Sequence[str], None] = 'b374524c5bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False, server_default='change@me.com'))
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_column('email')
    # ### end Alembic commands ###
