"""add_call_outcomes_table

Revision ID: a7454af90ea1
Revises: 4765f94e7c15
Create Date: 2026-05-04 01:52:13.683857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7454af90ea1'
down_revision: Union[str, Sequence[str], None] = '4765f94e7c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('primary_outcome', sa.String(length=255), nullable=True),
    sa.Column('outcome_value', sa.Float(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_talk_time', sa.Float(), nullable=True),
    sa.Column('customer_talk_time', sa.Float(), nullable=True),
    sa.Column('talk_ratio', sa.Float(), nullable=True),
    sa.Column('campaign_specific_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_outcomes_call_id'), 'call_outcomes', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_outcomes_id'), 'call_outcomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_outcomes_id'), table_name='call_outcomes')
    op.drop_index(op.f('ix_call_outcomes_call_id'), table_name='call_outcomes')
    op.drop_table('call_outcomes')
    # ### end Alembic commands ###
