"""extend_call_model

Revision ID: b374524c5bba
Revises: e3ab4a708d3a
Create Date: 2026-05-03 02:51:19.693281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b374524c5bba'
down_revision: Union[str, Sequence[str], None] = 'e3ab4a708d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_talk_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('customer_talk_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('lead_status', sa.Enum('HOT', 'WARM', 'COLD', name='leadstatus'), nullable=True))
        batch_op.add_column(sa.Column('is_golden_moment', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('call_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emotion_timeline', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_column('emotion_timeline')
        batch_op.drop_column('call_summary')
        batch_op.drop_column('is_golden_moment')
        batch_op.drop_column('lead_status')
        batch_op.drop_column('tags')
        batch_op.drop_column('customer_talk_time')
        batch_op.drop_column('agent_talk_time')
    # ### end Alembic commands ###
