"""task_65_intelligence_hub

Revision ID: c42e9d755115
Revises: a7454af90ea1
Create Date: 2026-05-04 03:54:10.075722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42e9d755115'
down_revision: Union[str, Sequence[str], None] = 'a7454af90ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('focus_area', sa.String(length=255), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=True),
    sa.Column('score_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_sessions_agent_id'), 'coaching_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_id'), 'coaching_sessions', ['id'], unique=False)
    op.create_table('call_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_annotations_call_id'), 'call_annotations', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_annotations_id'), 'call_annotations', ['id'], unique=False)
    op.create_table('call_qa_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('objection', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('customer_emotion_at', sa.String(length=50), nullable=True),
    sa.Column('customer_emotion_after', sa.String(length=50), nullable=True),
    sa.Column('is_golden_response', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_qa_pairs_call_id'), 'call_qa_pairs', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_qa_pairs_id'), 'call_qa_pairs', ['id'], unique=False)
    op.add_column('calls', sa.Column('call_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('call_hour', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('call_day_of_week', sa.String(length=15), nullable=True))
    op.add_column('calls', sa.Column('calls_before_this', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('acoustic_delta', sa.JSON(), nullable=True))
    op.add_column('calls', sa.Column('nlp_metrics', sa.JSON(), nullable=True))
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('transcript',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('transcript',
                   existing_type=sa.JSON(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    op.drop_column('calls', 'nlp_metrics')
    op.drop_column('calls', 'acoustic_delta')
    op.drop_column('calls', 'calls_before_this')
    op.drop_column('calls', 'call_day_of_week')
    op.drop_column('calls', 'call_hour')
    op.drop_column('calls', 'call_datetime')
    op.drop_index(op.f('ix_call_qa_pairs_id'), table_name='call_qa_pairs')
    op.drop_index(op.f('ix_call_qa_pairs_call_id'), table_name='call_qa_pairs')
    op.drop_table('call_qa_pairs')
    op.drop_index(op.f('ix_call_annotations_id'), table_name='call_annotations')
    op.drop_index(op.f('ix_call_annotations_call_id'), table_name='call_annotations')
    op.drop_table('call_annotations')
    op.drop_index(op.f('ix_coaching_sessions_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_agent_id'), table_name='coaching_sessions')
    op.drop_table('coaching_sessions')
    # ### end Alembic commands ###
