"""extend_employee_model

Revision ID: e3ab4a708d3a
Revises: f8ef5728bed2
Create Date: 2026-05-03 02:47:16.200108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ab4a708d3a'
down_revision: Union[str, Sequence[str], None] = 'f8ef5728bed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='employeetier'), nullable=False, server_default='BRONZE'))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('emotion_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('emotion_history')
        batch_op.drop_column('skills')
        batch_op.drop_column('tier')
        batch_op.drop_column('avatar')
    # ### end Alembic commands ###
