"""extend_campaign_model

Revision ID: f8ef5728bed2
Revises: 460d2f364752
Create Date: 2026-05-03 02:44:28.754582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ef5728bed2'
down_revision: Union[str, Sequence[str], None] = '460d2f364752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('SALES', 'CUSTOMER_SERVICE', 'TECHNICAL', 'COLLECTIONS', name='campaigntype'), nullable=False, server_default='CUSTOMER_SERVICE'))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('kpis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False, server_default='#6366f1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('kpis')
        batch_op.drop_column('status')
        batch_op.drop_column('type')
    # ### end Alembic commands ###
