import { useState } from 'react';
import { AlertTriangle, FileText, Download, Trash2, CheckCircle, Loader2, X } from 'lucide-react';
import { Campaign } from '../../lib/types';
import { cn } from '../ui/utils';

interface Props {
  campaign: Campaign;
  onClose: () => void;
  onConfirmDelete: () => void;
}

type Step = 'warn' | 'summary' | 'backup' | 'confirm';

export function GuardrailModal({ campaign, onClose, onConfirmDelete }: Props) {
  const [step, setStep] = useState<Step>('warn');
  const [summaryGenerated, setSummaryGenerated] = useState(false);
  const [backupDownloaded, setBackupDownloaded] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [summaryText, setSummaryText] = useState('');

  const handleGenerateSummary = async () => {
    setIsGenerating(true);
    await new Promise(r => setTimeout(r, 2200));
    setSummaryText(
      `FINAL CAMPAIGN SUMMARY — ${campaign.name}\n\nCampaign Type: ${campaign.type.replace('_', ' ').toUpperCase()}\nTotal Calls Analyzed: ${campaign.total_calls.toLocaleString()}\nAverage QA Score: ${campaign.avg_score}/100\nAgents Active: ${campaign.agent_count}\n\nKey Performance Summary:\n• ${campaign.kpis?.[0] || 'Quality'}: Exceeded target by 12%\n• ${campaign.kpis?.[1] || 'Empathy'}: Met baseline at 94th percentile\n\nAI-Generated Insights:\nThis campaign demonstrated strong fundamentals in ${campaign.type.replace('_', ' ')} execution. The Groq intelligence pipeline processed ${campaign.total_calls.toLocaleString()} calls.\n\nData archived on: ${new Date().toLocaleDateString()}\nGenerated by: VoiceQA Enterprise AI v2.4.1`
    );
    setSummaryGenerated(true);
    setIsGenerating(false);
  };

  const handleDownloadBackup = async () => {
    setIsDownloading(true);
    await new Promise(r => setTimeout(r, 1800));
    // Simulate download
    const blob = new Blob([JSON.stringify({ campaign, exportedAt: new Date().toISOString(), summary: summaryText }, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `campaign_backup_${campaign.id}_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setBackupDownloaded(true);
    setIsDownloading(false);
  };

  const canDelete = summaryGenerated && backupDownloaded;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />

      <div className="relative bg-card border border-border rounded-2xl w-full max-w-lg shadow-2xl">
        {/* Header */}
        <div className="flex items-center gap-3 px-6 py-4 border-b border-border">
          <div className="size-9 rounded-xl bg-red-500/15 flex items-center justify-center">
            <Trash2 size={18} className="text-red-400" />
          </div>
          <div className="flex-1">
            <h2 className="text-slate-100 text-sm font-semibold">Delete Campaign Guard</h2>
            <p className="text-muted-foreground text-xs">{campaign.name}</p>
          </div>
          <button onClick={onClose} className="size-8 flex items-center justify-center rounded-lg text-muted-foreground hover:text-foreground hover:bg-secondary transition-all">
            <X size={16} />
          </button>
        </div>

        <div className="px-6 py-5 space-y-4">
          {/* Warning banner */}
          <div className="flex gap-3 p-4 bg-red-500/8 border border-red-500/20 rounded-xl">
            <AlertTriangle size={18} className="text-red-400 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-red-300 text-sm font-medium">Irreversible Action — Complete All Steps First</p>
              <p className="text-muted-foreground text-xs mt-1">
                Deleting this campaign will permanently remove <strong className="text-foreground">{campaign.total_calls.toLocaleString()} calls</strong>, all transcripts, QA scores, and agent performance data. This cannot be undone.
              </p>
            </div>
          </div>

          {/* Step 1: Generate Summary */}
          <div className={cn(
            'p-4 rounded-xl border transition-all',
            summaryGenerated ? 'bg-emerald-500/8 border-emerald-500/20' : 'bg-secondary/50 border-border'
          )}>
            <div className="flex items-start gap-3">
              <div className={cn('size-7 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5', summaryGenerated ? 'bg-emerald-500/20' : 'bg-secondary')}>
                {summaryGenerated ? <CheckCircle size={14} className="text-emerald-400" /> : <FileText size={14} className="text-muted-foreground" />}
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <p className="text-sm text-foreground font-medium">Step 1: Generate Final Summary</p>
                  {!summaryGenerated && (
                    <button
                      onClick={handleGenerateSummary}
                      disabled={isGenerating}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-primary/15 text-primary hover:bg-primary/25 border border-indigo-500/30 rounded-lg text-xs transition-all disabled:opacity-50"
                    >
                      {isGenerating ? <Loader2 size={12} className="animate-spin" /> : <FileText size={12} />}
                      {isGenerating ? 'Generating...' : 'Generate'}
                    </button>
                  )}
                </div>
                <p className="text-xs text-muted-foreground mt-1">AI-generated campaign performance report with key metrics and insights.</p>
                {summaryGenerated && (
                  <pre className="mt-3 text-xs text-muted-foreground bg-background rounded-lg p-3 overflow-auto max-h-32 whitespace-pre-wrap leading-relaxed border border-border">
                    {summaryText}
                  </pre>
                )}
              </div>
            </div>
          </div>

          {/* Step 2: Download Backup */}
          <div className={cn(
            'p-4 rounded-xl border transition-all',
            !summaryGenerated ? 'opacity-40 pointer-events-none' : '',
            backupDownloaded ? 'bg-emerald-500/8 border-emerald-500/20' : 'bg-secondary/50 border-border'
          )}>
            <div className="flex items-start gap-3">
              <div className={cn('size-7 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5', backupDownloaded ? 'bg-emerald-500/20' : 'bg-secondary')}>
                {backupDownloaded ? <CheckCircle size={14} className="text-emerald-400" /> : <Download size={14} className="text-muted-foreground" />}
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <p className="text-sm text-foreground font-medium">Step 2: Download Full Data Backup</p>
                  {!backupDownloaded && (
                    <button
                      onClick={handleDownloadBackup}
                      disabled={isDownloading}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-cyan-500/15 text-cyan-400 hover:bg-cyan-500/25 border border-cyan-500/30 rounded-lg text-xs transition-all disabled:opacity-50"
                    >
                      {isDownloading ? <Loader2 size={12} className="animate-spin" /> : <Download size={12} />}
                      {isDownloading ? 'Packaging...' : 'Download ZIP/JSON'}
                    </button>
                  )}
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  Exports all calls, transcripts, and scores as a compressed JSON archive.
                </p>
                {backupDownloaded && (
                  <p className="text-xs text-emerald-400 mt-2">✓ Backup downloaded successfully</p>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex gap-3 px-6 py-4 border-t border-border">
          <button onClick={onClose} className="flex-1 px-4 py-2 bg-secondary hover:bg-secondary/80 text-foreground rounded-xl text-sm transition-all">
            Cancel
          </button>
          <button
            onClick={onConfirmDelete}
            disabled={!canDelete}
            className={cn(
              'flex-1 px-4 py-2 rounded-xl text-sm font-medium transition-all flex items-center justify-center gap-2',
              canDelete
                ? 'bg-red-500/20 border border-red-500/40 text-red-300 hover:bg-red-500/30'
                : 'bg-secondary text-muted-foreground cursor-not-allowed border border-border'
            )}
          >
            <Trash2 size={14} />
            {canDelete ? 'Permanently Delete Campaign' : 'Complete steps above'}
          </button>
        </div>
      </div>
    </div>
  );
}
